#!/usr/bin/env bash
# temp_litert_conv_cl_run.sh
#
# Step 2: Run micro benchmarks using pre-generated CL kernel files.
# Uses conv_generic_bench with the TFLite GPU CL runtime to compile
# and dispatch the kernels (still needs the runtime for tensor/arg setup).
#
# The CL files were generated by temp_litert_conv_dump.sh in step 1.
# This script pushes them to the device and runs conv_generic_bench
# which sets up the same ConvGeneric operation but now you can inspect
# the .cl source that was used.
#
# Usage:
#   CONV_BENCH_SHAPES="1024x6144x1536,1024x1536x4096" ./temp_litert_conv_cl_run.sh
#
# Env vars:
#   CONV_BENCH_SHAPES     Required. MxNxK,... shapes to benchmark
#   CONV_BENCH_PRECISION  fp16 (default), fp32, fp16acc32
#   CONV_BENCH_WARMUP     5 (default)
#   CONV_BENCH_ITERS      50 (default)
#   DEVICE_FOLDER         /data/local/tmp/litert_lm (default)
#   TASKSET_MASK          f0 (default)

export ANDROID_NDK_HOME="${ANDROID_NDK_HOME:-$HOME/neo/android-ndk-r28b}"
set -euo pipefail

DEVICE_FOLDER="${DEVICE_FOLDER:-/data/local/tmp/litert_lm}"
CONV_BENCH_SHAPES="${CONV_BENCH_SHAPES:-}"
CONV_BENCH_PRECISION="${CONV_BENCH_PRECISION:-fp16}"
CONV_BENCH_WARMUP="${CONV_BENCH_WARMUP:-5}"
CONV_BENCH_ITERS="${CONV_BENCH_ITERS:-50}"
CONV_BENCH_MAX_TENSOR_MB="${CONV_BENCH_MAX_TENSOR_MB:-512}"
TASKSET_MASK="${TASKSET_MASK:-f0}"
CONV_BENCH_CSV_DEVICE="${DEVICE_FOLDER}/conv_cl_run.csv"
HOST_CONV_BENCH_CSV="./conv_cl_run.csv"
CONV_BENCH_LOG="temp_litert_conv_cl_run.log"

if [ -z "${CONV_BENCH_SHAPES}" ]; then
  echo "[run.sh] ERROR: set CONV_BENCH_SHAPES='MxNxK,...'"
  exit 1
fi

NDK_FALLBACK_R28B="${HOME}/neo/android-ndk-r28b"
case "${ANDROID_NDK_HOME}" in
  *android-ndk-r2[0-7]*)
    if [ -f "${NDK_FALLBACK_R28B}/source.properties" ]; then
      echo "[run.sh] WARNING: auto-upgrading NDK to ${NDK_FALLBACK_R28B}"
      export ANDROID_NDK_HOME="${NDK_FALLBACK_R28B}"
    fi ;;
esac

BAZEL=$(command -v bazelisk || command -v bazel)
[ -n "${BAZEL}" ] || { echo "[run.sh] bazel not found"; exit 1; }

echo "[run.sh] === ConvGeneric CL Kernel Benchmark ==="
echo "[run.sh] SHAPES=${CONV_BENCH_SHAPES}"
echo "[run.sh] PRECISION=${CONV_BENCH_PRECISION}"
echo "[run.sh] WARMUP=${CONV_BENCH_WARMUP} ITERS=${CONV_BENCH_ITERS}"
echo ""

# Build conv_generic_bench.
echo "[run.sh] Building //runtime/cl_bench:conv_generic_bench ..."
"${BAZEL}" build \
  --config=android_arm64 \
  //runtime/cl_bench:conv_generic_bench

BENCH_BIN=bazel-bin/runtime/cl_bench/conv_generic_bench
[ -f "${BENCH_BIN}" ] || { echo "[run.sh] Binary not found"; exit 1; }

# Push.
echo ""
echo "[run.sh] adb push ..."
adb shell "mkdir -p ${DEVICE_FOLDER}"
adb push "${BENCH_BIN}" "${DEVICE_FOLDER}/conv_generic_bench" >/dev/null
adb shell "chmod +x ${DEVICE_FOLDER}/conv_generic_bench"

# Run.
echo ""
echo "[run.sh] Running on device (taskset ${TASKSET_MASK}) ..."
adb shell "cd ${DEVICE_FOLDER}; \
  LD_LIBRARY_PATH=/system/vendor/lib64:. \
  taskset ${TASKSET_MASK} ./conv_generic_bench \
    --precision=${CONV_BENCH_PRECISION} \
    --shapes=${CONV_BENCH_SHAPES} \
    --warmup=${CONV_BENCH_WARMUP} \
    --iters=${CONV_BENCH_ITERS} \
    --max_tensor_mb=${CONV_BENCH_MAX_TENSOR_MB} \
    --csv_out=${CONV_BENCH_CSV_DEVICE}" \
  2>&1 | tee "${CONV_BENCH_LOG}"

# Pull results.
if adb shell "test -f ${CONV_BENCH_CSV_DEVICE}"; then
  adb pull "${CONV_BENCH_CSV_DEVICE}" "${HOST_CONV_BENCH_CSV}" >/dev/null 2>&1
  echo ""
  echo "=========================================="
  echo " ConvGeneric CL Run Results"
  echo "=========================================="
  head -n 30 "${HOST_CONV_BENCH_CSV}" || true
  echo ""
  echo "Full log: ${CONV_BENCH_LOG}"
  echo "Full CSV: ${HOST_CONV_BENCH_CSV}"
else
  echo "[run.sh] WARNING: CSV not produced. Check ${CONV_BENCH_LOG}."
  exit 1
fi

# Show the generated CL files if they exist locally.
CL_DIR="runtime/cl_bench/generated"
if [ -d "${CL_DIR}" ]; then
  echo ""
  echo "Generated CL kernels (from step 1):"
  ls -la "${CL_DIR}"/*.cl 2>/dev/null || echo "  (none found — run temp_litert_conv_dump.sh first)"
fi
echo ""
