#!/usr/bin/env bash
# temp_litert.sh
#
# One-shot build + push + run for LiteRT-LM on Android / Adreno 830.
# Mirrors the nntrainer temp.sh workflow so the same iterate/inspect loop
# works here. Produces two things the reviewer wants:
#
#   1. Prefill/Decode TPS for Gemma 4 E2B on this device (baseline vs. the
#      official "3,808 t/s prefill" number which is on Samsung S26 Ultra GPU
#      -- Adreno 830 is one or two generations older so the absolute number
#      will be lower, but we compute the ratio to peak and % utilization).
#
#   2. Per-op LiteRT profile dump, in particular every MatMul /
#      FullyConnected / BatchMatMul row, so we can see which matmul-unit-op
#      dominates prefill. This comes from the --enable_op_profiling flag we
#      added in this branch, wired through AdvancedSettings ->
#      runtime_options.SetEnableProfiling(true) ->
#      LiteRtCompiledModelGetProfiler -> LiteRtGetProfileSummary (printed
#      by the executor destructor). See the [Phase A] commit for details.
#
# Prereqs (run these once, not in this script):
#   - Bazelisk / Bazel 7.6.1   (https://bazel.build/install)
#   - Android NDK r28b+        (https://developer.android.com/ndk/downloads)
#     export ANDROID_NDK_HOME=/path/to/AndroidNDK
#   - adb with a rooted / debuggable device connected
#   - ./download_gemma.sh      (fetches the model to ~/.cache/litert_lm_models)
#
# After running this (OP_PROFILING=true is the default) you should see a
# block ending with something like:
#
#   BenchmarkInfo:
#     Prefill Turns (Total 1 turns):
#       Prefill Turn 1: Processed 1024 tokens in <X>ms duration.
#         Prefill Speed: <1024*1000/X> tokens/sec.   ← compare to 3808 ref
#     Decode Turns (Total 1 turns):
#       Decode Turn 1: Processed 256 tokens in <Y>ms duration.
#         Decode Speed: <256*1000/Y> tokens/sec.
#
#   [PROFILE LiteRT CompiledModel per-op summary] (generated by
#    GetProfileSummary, --enable_op_profiling=true):
#     ... (per-op table including every matmul op) ...
#
# and the summary section at the bottom extracts:
#   - Prefill/Decode/Time-to-first-token lines
#   - Full LiteRT per-op summary table
#   - Matmul-unit-op rows only (FullyConnected / BatchMatMul / MatMul / Conv2D)
#   - Per-op-type rollup (how much time each op type took across the run)
#
# The decode output in --benchmark_prefill_tokens=1024 mode is a stream of
# <pad> tokens because session_utils.cc:72 zero-pads the tokenized input to
# 1024 tokens. That is expected and orthogonal to the matmul numbers. If
# you want real English decode output for a sanity check, run once with
# OP_PROFILING=false (which ALSO disables the per-op table, and the prompt
# runs at its natural 18-token length).
#
# Paste the whole summary block into error.txt for the next iteration.
#
# Env overrides:
#   DEVICE_FOLDER   where to push on device (default /data/local/tmp/litert_lm)
#   MODEL_PATH      path to .litertlm on host (default ~/.cache/litert_lm_models/gemma-4-E2B-it.litertlm)
#   PREFILL_TOKENS  benchmark prefill length (default 1024, matches Google's table)
#   DECODE_TOKENS   benchmark decode length  (default 256,  matches Google's table)
#   ASYNC           async prefill flag       (default false, required when benchmark_prefill_tokens>0)
#   TASKSET_MASK    taskset mask for big core pinning (default f0 = big cluster on SD8E)
#   OP_PROFILING    --enable_op_profiling toggle (default TRUE).
#                   Yes, true. Here is the rationale:
#                     - Prior runs confirmed that SetEnableProfiling(true) at
#                       CompiledModel::Create time perturbs the OpenCL delegate
#                       on Adreno 830 enough to corrupt decode output (we got
#                       " Hungaryफ्राФа" instead of real text).
#                     - BUT the benchmark path with
#                       --benchmark_prefill_tokens=1024 already produces
#                       meaningless output: session_utils.cc:72 resizes the
#                       tokenized input to 1024 tokens by zero-padding, so the
#                       decode step runs on an all-pad context and emits a
#                       stream of <pad> tokens. The decoded text is already
#                       garbage-by-design in this mode.
#                     - Timing measurements (Prefill/Decode tokens-per-sec)
#                       and per-op profile tables are both orthogonal to
#                       decode correctness. They remain valid under profiling.
#                     - The entire point of this script is to collect the
#                       per-op matmul profile table so we can identify which
#                       FullyConnected / MatMul / BatchMatMul op dominates
#                       prefill on Adreno 830. That *requires* OP_PROFILING.
#                   So the default for a benchmark run is TRUE. If you only
#                   want the correctness sanity check (real prompt, real
#                   answer), set OP_PROFILING=false and the script drops the
#                   --enable_op_profiling flag.

# NDK r28b or newer is required. r26d fails to compile crate_index__cxx-1.0.149
# because its libc++ does not satisfy std::ranges::contiguous_range for
# rust::Slice::iterator (see docs/getting-started/build-and-run.md).
# Respect the caller's ANDROID_NDK_HOME if already exported; otherwise default
# to r28b under ~/neo/.
export ANDROID_NDK_HOME="${ANDROID_NDK_HOME:-$HOME/neo/android-ndk-r28b}"

set -euo pipefail

# ----------------------------------------------------------------------------
# 1. Configure
# ----------------------------------------------------------------------------
DEVICE_FOLDER="${DEVICE_FOLDER:-/data/local/tmp/litert_lm}"
MODEL_PATH_HOST="${MODEL_PATH:-$HOME/.cache/litert_lm_models/gemma-4-E2B-it.litertlm}"
PREFILL_TOKENS="${PREFILL_TOKENS:-1024}"
DECODE_TOKENS="${DECODE_TOKENS:-256}"
ASYNC="${ASYNC:-false}"
TASKSET_MASK="${TASKSET_MASK:-f0}"
OP_PROFILING="${OP_PROFILING:-true}"
# Matmul micro benchmark: if true, runs matmul_micro_benchmark after the
# main prefill/decode run, against the CSV matmul roster emitted by the
# in-executor shape dumper. Only meaningful when OP_PROFILING=true,
# since that's when the roster CSV is produced.
MATMUL_MICRO="${MATMUL_MICRO:-true}"
MATMUL_MICRO_WARMUP="${MATMUL_MICRO_WARMUP:-5}"
MATMUL_MICRO_ITERS="${MATMUL_MICRO_ITERS:-50}"
# fp32 is the only dtype that survives the LiteRT CPU FC fallback path
# right now (the CPU FC reference kernel asserts input->type ==
# kTfLiteFloat32, so a FLOAT16-tensor model fails to prepare). The
# GPU CL delegate still compiles fp16 kernels under the hood via
# GpuOptions::SetPrecision(kFp16), which matches Gemma4 prefill.
MATMUL_MICRO_DTYPE="${MATMUL_MICRO_DTYPE:-fp32}"

# Normalize OP_PROFILING (accept 1/true/yes/on as true).
case "${OP_PROFILING,,}" in
  1|true|yes|on)  OP_PROFILING=true  ;;
  0|false|no|off|"") OP_PROFILING=false ;;
  *)
    echo "[temp_litert.sh] OP_PROFILING must be true/false (got '${OP_PROFILING}')"
    exit 1
    ;;
esac

if [ ! -f "${MODEL_PATH_HOST}" ]; then
  echo "[temp_litert.sh] Model not found: ${MODEL_PATH_HOST}"
  echo "[temp_litert.sh] Run ./download_gemma.sh first."
  exit 1
fi
if [ -z "${ANDROID_NDK_HOME:-}" ]; then
  echo "[temp_litert.sh] ANDROID_NDK_HOME is not set. Export it before running."
  echo "    export ANDROID_NDK_HOME=/path/to/AndroidNDK"
  exit 1
fi
NDK_FALLBACK_R28B="${HOME}/neo/android-ndk-r28b"

# Auto-upgrade from a stale NDK < r28 when r28b is already installed at the
# canonical location. This handles the common case where the user has a
# `export ANDROID_NDK_HOME=.../android-ndk-r26d` line in ~/.bashrc that
# silently overrides the default set at the top of this script.
case "${ANDROID_NDK_HOME}" in
  *android-ndk-r2[0-7]*)
    if [ -f "${NDK_FALLBACK_R28B}/README.md" ] \
       && [ -f "${NDK_FALLBACK_R28B}/source.properties" ]; then
      echo "[temp_litert.sh] WARNING: caller exported ANDROID_NDK_HOME=${ANDROID_NDK_HOME}"
      echo "[temp_litert.sh]          but that NDK is too old (crate_index__cxx-1.0.149"
      echo "[temp_litert.sh]          won't compile). Auto-upgrading to:"
      echo "[temp_litert.sh]          ${NDK_FALLBACK_R28B}"
      echo "[temp_litert.sh]          To silence this warning permanently, update ~/.bashrc:"
      echo "[temp_litert.sh]            export ANDROID_NDK_HOME=${NDK_FALLBACK_R28B}"
      export ANDROID_NDK_HOME="${NDK_FALLBACK_R28B}"
    else
      echo "[temp_litert.sh] ANDROID_NDK_HOME looks like NDK < r28: ${ANDROID_NDK_HOME}"
      echo "[temp_litert.sh] crate_index__cxx-1.0.149 will not compile against this NDK's libc++."
      echo "[temp_litert.sh] Install r28b and re-run:"
      echo "    ./install_android_ndk.sh"
      echo "    unset ANDROID_NDK_HOME    # or: export ANDROID_NDK_HOME=${NDK_FALLBACK_R28B}"
      echo "    ./temp_litert.sh"
      exit 1
    fi
    ;;
esac

if [ ! -d "${ANDROID_NDK_HOME}" ]; then
  echo "[temp_litert.sh] ANDROID_NDK_HOME does not exist: ${ANDROID_NDK_HOME}"
  echo "[temp_litert.sh] Install NDK r28b or newer with:"
  echo "    ./install_android_ndk.sh"
  echo "[temp_litert.sh] or from"
  echo "    https://developer.android.com/ndk/downloads#stable-downloads"
  exit 1
fi

BAZEL=$(command -v bazelisk || command -v bazel)
if [ -z "${BAZEL}" ]; then
  echo "[temp_litert.sh] Neither bazelisk nor bazel found in PATH."
  exit 1
fi

echo "[temp_litert.sh] BAZEL=${BAZEL}"
echo "[temp_litert.sh] ANDROID_NDK_HOME=${ANDROID_NDK_HOME}"
echo "[temp_litert.sh] MODEL (host)=${MODEL_PATH_HOST}"
echo "[temp_litert.sh] DEVICE_FOLDER=${DEVICE_FOLDER}"
echo "[temp_litert.sh] PREFILL_TOKENS=${PREFILL_TOKENS}"
echo "[temp_litert.sh] DECODE_TOKENS=${DECODE_TOKENS}"
echo "[temp_litert.sh] ASYNC=${ASYNC}"
echo "[temp_litert.sh] TASKSET_MASK=${TASKSET_MASK}"
echo "[temp_litert.sh] OP_PROFILING=${OP_PROFILING}"
if [ "${OP_PROFILING}" = "true" ]; then
  echo "[temp_litert.sh]   (per-op profile table WILL be emitted. Expect the"
  echo "[temp_litert.sh]    decode stream to be <pad> tokens because the 1024-"
  echo "[temp_litert.sh]    token synthetic prefill feeds a zero-padded context"
  echo "[temp_litert.sh]    to the model. Decoded text is garbage-by-design in"
  echo "[temp_litert.sh]    benchmark mode; only Prefill/Decode tokens-per-sec"
  echo "[temp_litert.sh]    and the [PROFILE LiteRT CompiledModel per-op]"
  echo "[temp_litert.sh]    summary at the bottom matter. DO NOT Ctrl+C --"
  echo "[temp_litert.sh]    decode takes roughly 8s and the profile summary"
  echo "[temp_litert.sh]    only prints on clean exit.)"
else
  echo "[temp_litert.sh]   (per-op profile summary will NOT be emitted this run."
  echo "[temp_litert.sh]    Set OP_PROFILING=false only when you want to verify"
  echo "[temp_litert.sh]    the decode output is not garbled on a real prompt.)"
fi
echo ""

# ----------------------------------------------------------------------------
# 2. Build litert_lm_main for android_arm64 with GPU accelerator shlibs.
#    The two --define flags follow docs/getting-started/build-and-run.md:
#    they tell LiteRT to link the C API via a separate libLiteRtRuntimeCApi.so
#    (so the GPU accelerator shlib can dlopen it) and skip resolving the
#    C symbols statically in the main binary.
# ----------------------------------------------------------------------------
echo "[temp_litert.sh] Building //runtime/engine:litert_lm_main ..."
BAZEL_TARGETS=(//runtime/engine:litert_lm_main)
if [ "${MATMUL_MICRO}" = "true" ]; then
  BAZEL_TARGETS+=(//runtime/engine:matmul_micro_benchmark)
fi
"${BAZEL}" build \
  --config=android_arm64 \
  --define=litert_link_capi_so=true \
  --define=resolve_symbols_in_exec=false \
  "${BAZEL_TARGETS[@]}"

BIN=bazel-bin/runtime/engine/litert_lm_main
if [ ! -x "${BIN}" ] && [ ! -f "${BIN}" ]; then
  echo "[temp_litert.sh] Build succeeded but binary not at expected path ${BIN}"
  exit 1
fi

MATMUL_MICRO_BIN=bazel-bin/runtime/engine/matmul_micro_benchmark
if [ "${MATMUL_MICRO}" = "true" ] && \
   [ ! -x "${MATMUL_MICRO_BIN}" ] && [ ! -f "${MATMUL_MICRO_BIN}" ]; then
  echo "[temp_litert.sh] matmul_micro_benchmark binary not found at"
  echo "    ${MATMUL_MICRO_BIN}"
  echo "    set MATMUL_MICRO=false to skip"
  exit 1
fi

# Locate libLiteRt.so. With --define=litert_link_capi_so=true the C runtime
# is in a separate shared library that bazel writes somewhere under
# bazel-bin/external/litert/. Search for it instead of hard-coding the path,
# because the layout depends on rules_cc / cc_shared_library implementation
# details.
LIBLITERT_SO=$(find -L bazel-bin -maxdepth 8 -type f -name "libLiteRt.so" \
                  ! -path "*solib*" 2>/dev/null | head -1)
if [ -z "${LIBLITERT_SO}" ]; then
  # Some versions place it inside a _solib_ tree. Fall back.
  LIBLITERT_SO=$(find -L bazel-bin -type f -name "libLiteRt.so" 2>/dev/null | head -1)
fi
if [ -z "${LIBLITERT_SO}" ]; then
  echo "[temp_litert.sh] Built libLiteRt.so not found under bazel-bin/."
  echo "    Did the build target really resolve --define=litert_link_capi_so=true?"
  echo "    Try: ${BAZEL} build --config=android_arm64 --define=litert_link_capi_so=true \\"
  echo "                        --define=resolve_symbols_in_exec=false \\"
  echo "                        @litert//litert/c:libLiteRt.so"
  exit 1
fi
echo "[temp_litert.sh] libLiteRt.so : ${LIBLITERT_SO}"

# Inventory of GPU accelerator shlibs that need to live next to the binary on
# the device. These are LFS-tracked prebuilts in the upstream LiteRT-LM repo;
# this branch was imported without them. fetch_android_prebuilts.sh downloads
# them from upstream.
REQUIRED_PREBUILTS=(
  libLiteRtGpuAccelerator.so
  libLiteRtOpenClAccelerator.so
  libLiteRtTopKOpenClSampler.so
  libLiteRtTopKWebGpuSampler.so
  libLiteRtWebGpuAccelerator.so
  libGemmaModelConstraintProvider.so
)
PREBUILT_DIR=prebuilt/android_arm64
MISSING_PREBUILTS=()
for f in "${REQUIRED_PREBUILTS[@]}"; do
  if [ ! -f "${PREBUILT_DIR}/${f}" ]; then
    MISSING_PREBUILTS+=("${f}")
  fi
done
if [ "${#MISSING_PREBUILTS[@]}" -gt 0 ]; then
  echo "[temp_litert.sh] Missing GPU accelerator shlibs in ${PREBUILT_DIR}:"
  for f in "${MISSING_PREBUILTS[@]}"; do
    echo "    - ${f}"
  done
  echo "[temp_litert.sh] These are LFS-tracked in upstream LiteRT-LM. Fetch with:"
  echo "    ./fetch_android_prebuilts.sh"
  echo "[temp_litert.sh] Without them, --backend=gpu will not load any accelerator at runtime."
  exit 1
fi

# ----------------------------------------------------------------------------
# 3. Push binary + prebuilt GPU shlibs + model to device.
# ----------------------------------------------------------------------------
echo ""
echo "[temp_litert.sh] adb push binary + prebuilts + model ..."
adb shell "mkdir -p ${DEVICE_FOLDER}"
adb push "${BIN}" "${DEVICE_FOLDER}/litert_lm_main" >/dev/null
adb push "${LIBLITERT_SO}" "${DEVICE_FOLDER}/libLiteRt.so" >/dev/null
if [ "${MATMUL_MICRO}" = "true" ]; then
  adb push "${MATMUL_MICRO_BIN}" "${DEVICE_FOLDER}/matmul_micro_benchmark" \
    >/dev/null
fi

for f in "${REQUIRED_PREBUILTS[@]}"; do
  adb push "${PREBUILT_DIR}/${f}" "${DEVICE_FOLDER}/${f}" >/dev/null
done

# Model push is expensive. Only push if the on-device copy is smaller
# than the host one (assume truncated) or missing entirely.
MODEL_BASENAME=$(basename "${MODEL_PATH_HOST}")
HOST_SIZE=$(stat -c '%s' "${MODEL_PATH_HOST}" 2>/dev/null || stat -f '%z' "${MODEL_PATH_HOST}")
DEV_SIZE=$(adb shell "stat -c '%s' ${DEVICE_FOLDER}/${MODEL_BASENAME} 2>/dev/null || echo 0" | tr -d '\r')
if [ "${DEV_SIZE}" = "${HOST_SIZE}" ]; then
  echo "[temp_litert.sh] Model already on device, size matches (${HOST_SIZE} bytes). Skipping push."
else
  echo "[temp_litert.sh] Pushing model (${HOST_SIZE} bytes) ..."
  adb push "${MODEL_PATH_HOST}" "${DEVICE_FOLDER}/${MODEL_BASENAME}"
fi

adb shell "chmod +x ${DEVICE_FOLDER}/litert_lm_main"
if [ "${MATMUL_MICRO}" = "true" ]; then
  adb shell "chmod +x ${DEVICE_FOLDER}/matmul_micro_benchmark"
fi

# ----------------------------------------------------------------------------
# 4. Run with benchmark (and optionally op profiling). Capture stdout AND
#    stderr so the [PROFILE LiteRT CompiledModel per-op summary] dump from
#    the executor destructor lands in the same log as the BenchmarkInfo
#    output (when OP_PROFILING=true).
#
#    IMPORTANT: write to temp_litert_run.log, NOT error.txt. error.txt is
#    the reviewer-owned snapshot (same convention as nntrainer temp.sh).
#
#    Why default OP_PROFILING=false: empirically, SetEnableProfiling(true)
#    at CompiledModel::Create time makes LiteRT rebuild the OpenCL delegate
#    graph with instrumentation (begin/end around every op dispatch) and
#    this perturbs persistent-tensor aliasing on Adreno 830, which turns
#    the decoded Gemma 4 output into a garbage token stream. Until the
#    delegate bug is understood, the default path runs without profiling
#    so the decode output is verifiable.
# ----------------------------------------------------------------------------
RUN_LOG=temp_litert_run.log
MATMUL_ROSTER_CSV_DEVICE=${DEVICE_FOLDER}/matmul_roster.csv
MATMUL_MICRO_CSV_DEVICE=${DEVICE_FOLDER}/matmul_micro.csv
MATMUL_MICRO_LOG=temp_litert_matmul_micro.log
echo ""
echo "[temp_litert.sh] Running on device (taskset ${TASKSET_MASK}, op_profiling=${OP_PROFILING})..."
# LITERT_LM_MATMUL_ROSTER_CSV tells runtime/util/matmul_shape_dump.cc
# (invoked from the executor factory when --enable_op_profiling=true)
# to also write a machine-readable CSV next to its stderr dump. That
# CSV is the shape list the micro benchmark will consume in step 6.
adb shell "cd ${DEVICE_FOLDER}; \
  LD_LIBRARY_PATH=. \
  LITERT_LM_MATMUL_ROSTER_CSV=${MATMUL_ROSTER_CSV_DEVICE} \
  taskset ${TASKSET_MASK} ./litert_lm_main \
    --backend=gpu \
    --model_path=${DEVICE_FOLDER}/${MODEL_BASENAME} \
    --benchmark=true \
    --benchmark_prefill_tokens=${PREFILL_TOKENS} \
    --benchmark_decode_tokens=${DECODE_TOKENS} \
    --async=${ASYNC} \
    --report_peak_memory_footprint=true \
    --enable_op_profiling=${OP_PROFILING}" \
  2>&1 | tee "${RUN_LOG}"

# ----------------------------------------------------------------------------
# 5. Diagnostic summary (extracted from temp_litert_run.log for quick scan).
# ----------------------------------------------------------------------------
echo ""
echo "=========================================="
echo " Run summary (temp_litert.sh, OP_PROFILING=${OP_PROFILING})"
echo "=========================================="

echo ""
echo "--- Benchmark perf summary ---"
grep -E "Prefill Speed|Decode Speed|Prefill Turn|Decode Turn|Time to first token|peak memory" \
  "${RUN_LOG}" || echo "(no BenchmarkInfo lines found; run probably crashed)"

if [ "${OP_PROFILING}" = "true" ]; then
  # LiteRT prints two profile sections when --enable_op_profiling=true, and
  # understanding the difference is critical for reading the output:
  #
  # (a) The classic tflite::Profiler table ("Run Order" / "Top by Computation
  #     Time" / "Summary by node type"). On our prefill_1024 run this table
  #     reports "Number of nodes executed: 0" -- NOT because profiling is
  #     broken, but because the GPU delegate ate every op in the graph:
  #     "Replacing 1107 out of 1107 node(s) with delegate (LITERT_CL)".
  #     From the interpreter's perspective only one node (the delegate)
  #     ran, and the interpreter's profiler doesn't see anything below it.
  #
  # (b) The "Delegate Statistics" table that follows. THIS is the one with
  #     the real matmul data. The GPU delegate profiles its own per-kernel
  #     dispatches and dumps them as "Op Name | Count | Avg(us) | Min(us) |
  #     Max(us) | Total(us)", where op names use the OpenCL kernel fusion
  #     form, e.g. "convolution_int8(conv_wave_memory) -> dequantize_to_float16
  #     -> quantize_and_dequantize". Matmul shows up as `convolution(...)`
  #     because the GPU CL delegate implements matmul as 1x1 conv with a
  #     GEMM tiling strategy called conv_wave_memory.
  # Matmul shape roster: printed at CompiledModel::Create time by
  # runtime/util/matmul_shape_dump.cc (called from the executor factory
  # when --enable_op_profiling=true). One line per FULLY_CONNECTED /
  # BATCH_MATMUL / 1x1 CONV_2D op in the prefill/decode subgraph with the
  # actual M/N/K. Used to correlate fused kernel names like
  # `convolution_int8(conv_wave_memory)` against the source matmul
  # dimensions so we can identify which shape dominates prefill.
  echo ""
  echo "--- Matmul shape roster (from [PROFILE MATMUL SHAPES] block) ---"
  awk '/\[PROFILE MATMUL SHAPES\]/{found=1} found{
         print;
         if (/^$/ && printed) {exit}
         if (/\[PROFILE MATMUL SHAPES\]/) {printed=1}
       }' "${RUN_LOG}" \
    || echo "(no matmul shape roster -- did the executor factory run with enable_op_profiling=true? is runtime/util/matmul_shape_dump linked into the build?)"

  echo ""
  echo "--- LiteRT per-op summary (FULL table, no head limit) ---"
  echo "(tflite::Profiler section will show 'Number of nodes executed: 0'"
  echo " because every op is inside a single LITERT_CL delegate partition."
  echo " Real per-kernel data is in the Delegate Statistics section.)"
  awk '/PROFILE LiteRT CompiledModel per-op summary/{found=1} found{print}' \
    "${RUN_LOG}" \
    || echo "(no per-op summary -- was --enable_op_profiling=true threaded through? Did the build include the @litert//litert/c:litert_profiler dep? Did the destructor actually run, i.e. the process exited cleanly?)"

  # Matmul extraction. The GPU CL delegate labels matmul as `convolution`
  # (lowercase, not Conv2D / CONV_2D) because it uses the 1x1 conv GEMM
  # path. Cover both `convolution(` (fp16 path) and `convolution_int8(`
  # (int8 weight path with dequant-requant fusion). Upstream LiteRT may
  # also still print FULLY_CONNECTED / BATCH_MATMUL names in future
  # versions or on other backends (WebGPU), so the regex keeps those too.
  #
  # Skip the "convert_uint4_to_int8" / "quantize_float16_to_uint8c16" lines
  # -- those are weight / activation quantization helpers, not the matmul
  # compute, and pollute the view. Also skip the per-op-type header line
  # ("Delegate/...") with an exact-match guard on the whitespace+Count
  # column shape.
  echo ""
  echo "--- Matmul-unit-op rows (convolution / FullyConnected / BatchMatMul) ---"
  awk '/Delegate Statistics/,/^$/' "${RUN_LOG}" \
    | grep -Ei "Delegate/convolution|Delegate/.*(FullyConnected|BatchMatMul|MatMul|FULLY_CONNECTED|BATCH_MATMUL)" \
    | grep -v "weights_convert" \
    || echo "(no matmul-unit-op rows found in Delegate Statistics)"

  # Top-10 most expensive GPU kernel dispatches by total time. This is the
  # single most useful view for "which matmul shape should we optimize
  # first". Sort by the Total(us) column (the 6th whitespace-delimited
  # field), descending, and take the first 10.
  #
  # The Delegate Statistics block starts at "Delegate Statistics:" and
  # ends at the first blank line. Within that, rows look like:
  #   "Delegate/convolution(conv_wave_memory)     28     910.21     801    1563    25486"
  # Whitespace-separated with a possibly-multi-word op name on the left.
  # Awk approach: keep only lines starting with "Delegate/", use $NF-3..$NF
  # for the count/avg/min/max/total columns ($NF is Total(us)).
  echo ""
  echo "--- Top 10 GPU kernel dispatches by total time (Delegate/... rows) ---"
  awk '/Delegate Statistics/,/^$/' "${RUN_LOG}" \
    | awk '/^Delegate\//{print $NF, $0}' \
    | sort -k1,1 -n -r \
    | head -10 \
    | awk '{$1=""; sub(/^ /, ""); print}' \
    || true

  # Aggregate totals: how much time is matmul vs everything else in the
  # delegate statistics. Numbers like "matmul_total=<X> us, other=<Y> us,
  # matmul%=<X/(X+Y)>" are the headline number we care about.
  echo ""
  echo "--- Matmul vs. non-matmul aggregate (Delegate Statistics) ---"
  awk '/Delegate Statistics/,/^$/' "${RUN_LOG}" \
    | awk '
      /^Delegate\//{
        total = $NF
        if (/convolution\(/ || /convolution_int8\(/) {
          matmul += total
        } else {
          other += total
        }
      }
      END {
        sum = matmul + other
        if (sum > 0) {
          printf "matmul total     = %10.3f ms (%5.1f%% of instrumented)\n",
                 matmul / 1000.0, 100.0 * matmul / sum
          printf "non-matmul total = %10.3f ms (%5.1f%% of instrumented)\n",
                 other / 1000.0, 100.0 * other / sum
          printf "instrumented sum = %10.3f ms\n", sum / 1000.0
        } else {
          print "(no Delegate/ rows found)"
        }
      }'
else
  echo ""
  echo "--- Per-op profile summary: skipped (OP_PROFILING=false) ---"
  echo "You ran with OP_PROFILING=false, so no per-op table was collected."
  echo "To collect the matmul per-op table, re-run with:"
  echo "    OP_PROFILING=true ./temp_litert.sh     (or just ./temp_litert.sh"
  echo "                                             since the default is true)"
fi

# Always print the decode output at the end of the summary so the reviewer
# can eyeball whether it was real text (OP_PROFILING=false path) or the
# expected <pad> stream (OP_PROFILING=true path with synthetic prefill).
# If OP_PROFILING=true, <pad> here is expected and not a regression.
echo ""
echo "--- input_prompt + decode output (eyeball check) ---"
echo "  (OP_PROFILING=true: expect a stream of <pad> tokens, that is"
echo "   normal because benchmark_prefill_tokens=1024 zero-pads the"
echo "   input. The numbers above are the real answer.)"
awk '/^input_prompt:/{found=1} found{print; if (/BenchmarkInfo|Prefill Turn|PROFILE LiteRT/) exit}' \
  "${RUN_LOG}" \
  || echo "(no input_prompt line found; run probably crashed before decode)"


# ----------------------------------------------------------------------------
# 6. Matmul micro benchmark. Reads the matmul_roster.csv emitted by the
#    in-executor shape dumper (step 4) and runs matmul_micro_benchmark
#    on the same device, producing per-shape timing that can be placed
#    next to the Delegate Statistics from the prefill run. Each entry
#    is (M, N, K) -> min/avg/p50/p95/max us + gflops + tflops throughput.
#
#    To skip: MATMUL_MICRO=false
# ----------------------------------------------------------------------------
if [ "${MATMUL_MICRO}" = "true" ] && [ "${OP_PROFILING}" = "true" ]; then
  echo ""
  echo "=========================================="
  echo " Matmul micro benchmark"
  echo "=========================================="
  # Make sure the roster CSV actually got written on the device.
  ROSTER_SIZE=$(adb shell "stat -c '%s' ${MATMUL_ROSTER_CSV_DEVICE} 2>/dev/null || echo 0" | tr -d '\r')
  if [ -z "${ROSTER_SIZE}" ] || [ "${ROSTER_SIZE}" = "0" ]; then
    echo "[temp_litert.sh] WARNING: matmul roster CSV missing on device at"
    echo "    ${MATMUL_ROSTER_CSV_DEVICE}"
    echo "    (was LITERT_LM_MATMUL_ROSTER_CSV honored? check temp_litert_run.log"
    echo "     for '[PROFILE MATMUL SHAPES] CSV roster written to' line)"
  else
    echo "[temp_litert.sh] Running matmul_micro_benchmark against ${MATMUL_ROSTER_CSV_DEVICE} (${ROSTER_SIZE} bytes)..."
    adb shell "cd ${DEVICE_FOLDER}; \
      LD_LIBRARY_PATH=. \
      taskset ${TASKSET_MASK} ./matmul_micro_benchmark \
        --backend=gpu \
        --dtype=${MATMUL_MICRO_DTYPE} \
        --shapes_csv=${MATMUL_ROSTER_CSV_DEVICE} \
        --warmup=${MATMUL_MICRO_WARMUP} \
        --iters=${MATMUL_MICRO_ITERS} \
        --csv_out=${MATMUL_MICRO_CSV_DEVICE}" \
      2>&1 | tee "${MATMUL_MICRO_LOG}"

    # Pull the per-shape CSV to the host for post-processing.
    if adb shell "test -f ${MATMUL_MICRO_CSV_DEVICE}"; then
      adb pull "${MATMUL_MICRO_CSV_DEVICE}" ./matmul_micro.csv >/dev/null 2>&1
      echo ""
      echo "--- Matmul micro CSV (pulled to ./matmul_micro.csv) ---"
      echo "    Compare rows against the prefill Delegate Statistics above:"
      echo "    the per-(M,N,K) timing here explains which shapes are the"
      echo "    hot matmul kernels that show up as aggregated"
      echo "    convolution(conv_wave_memory) / convolution_int8(...) rows"
      echo "    in the Delegate table."
      head -n 20 ./matmul_micro.csv || true
    else
      echo ""
      echo "[temp_litert.sh] WARNING: matmul_micro.csv not produced on device."
    fi
  fi
fi

echo ""
echo "Full log: ${RUN_LOG}"
if [ "${MATMUL_MICRO}" = "true" ] && [ "${OP_PROFILING}" = "true" ]; then
  echo "Matmul micro log: ${MATMUL_MICRO_LOG}"
  echo "Matmul micro CSV (host): ./matmul_micro.csv"
fi
echo ""
