#!/usr/bin/env bash
# temp_litert.sh
#
# One-shot build + push + run for LiteRT-LM on Android / Adreno 830.
# Mirrors the nntrainer temp.sh workflow so the same iterate/inspect loop
# works here. Produces two things the reviewer wants:
#
#   1. Prefill/Decode TPS for Gemma 4 E2B on this device (baseline vs. the
#      official "3,808 t/s prefill" number which is on Samsung S26 Ultra GPU
#      -- Adreno 830 is one or two generations older so the absolute number
#      will be lower, but we compute the ratio to peak and % utilization).
#
#   2. Per-op LiteRT profile dump, in particular every MatMul /
#      FullyConnected / BatchMatMul row, so we can see which matmul-unit-op
#      dominates prefill. This comes from the --enable_op_profiling flag we
#      added in this branch, wired through AdvancedSettings ->
#      runtime_options.SetEnableProfiling(true) ->
#      LiteRtCompiledModelGetProfiler -> LiteRtGetProfileSummary (printed
#      by the executor destructor). See the [Phase A] commit for details.
#
# Prereqs (run these once, not in this script):
#   - Bazelisk / Bazel 7.6.1   (https://bazel.build/install)
#   - Android NDK r28b+        (https://developer.android.com/ndk/downloads)
#     export ANDROID_NDK_HOME=/path/to/AndroidNDK
#   - adb with a rooted / debuggable device connected
#   - ./download_gemma.sh      (fetches the model to ~/.cache/litert_lm_models)
#
# After running this you should see a block ending with something like:
#
#   --- input_prompt + decode output (sanity check that text is not garbled) ---
#   input_prompt: What is the tallest building in the world?
#   The tallest building in the world is the Burj Khalifa ...
#
#   BenchmarkInfo:
#     Prefill Turns (Total 1 turns):
#       Prefill Turn 1: ...
#         Prefill Speed: <xxx.xx> tokens/sec.
#     Decode Turns (Total 1 turns):
#       Decode Turn 1: ...
#         Decode Speed: <yy.yy> tokens/sec.
#
# Only when OP_PROFILING=true, you also get:
#
#   [PROFILE LiteRT CompiledModel per-op summary] (generated by GetProfileSummary, --enable_op_profiling=true):
#     ... (per-op table including every matmul op) ...
#
# The default run has OP_PROFILING=false so the decode output is correct.
# Run once like this to confirm the text is sensible, then re-run with
# OP_PROFILING=true to collect the per-op matmul table.
#
# Paste the whole summary block into error.txt for the next iteration.
#
# Env overrides:
#   DEVICE_FOLDER   where to push on device (default /data/local/tmp/litert_lm)
#   MODEL_PATH      path to .litertlm on host (default ~/.cache/litert_lm_models/gemma-4-E2B-it.litertlm)
#   PREFILL_TOKENS  benchmark prefill length (default 1024, matches Google's table)
#   DECODE_TOKENS   benchmark decode length  (default 256,  matches Google's table)
#   ASYNC           async prefill flag       (default false, required when benchmark_prefill_tokens>0)
#   TASKSET_MASK    taskset mask for big core pinning (default f0 = big cluster on SD8E)
#   OP_PROFILING    --enable_op_profiling toggle (default false).
#                   Previous runs on Adreno 830 with OP_PROFILING=true produced
#                   garbled decode output ("Hungaryफ्राФа"-style token stream),
#                   because runtime_options.SetEnableProfiling(true) makes
#                   LiteRT rebuild the GPU delegate graph with profiling
#                   instrumentation, which perturbs the OpenCL command queue
#                   and persistent-tensor aliasing on this device. Default is
#                   off so the baseline decode produces correct text; flip to
#                   OP_PROFILING=true only when you need the per-op summary
#                   and are ok with a separate (possibly garbled) run.

# NDK r28b or newer is required. r26d fails to compile crate_index__cxx-1.0.149
# because its libc++ does not satisfy std::ranges::contiguous_range for
# rust::Slice::iterator (see docs/getting-started/build-and-run.md).
# Respect the caller's ANDROID_NDK_HOME if already exported; otherwise default
# to r28b under ~/neo/.
export ANDROID_NDK_HOME="${ANDROID_NDK_HOME:-$HOME/neo/android-ndk-r28b}"

set -euo pipefail

# ----------------------------------------------------------------------------
# 1. Configure
# ----------------------------------------------------------------------------
DEVICE_FOLDER="${DEVICE_FOLDER:-/data/local/tmp/litert_lm}"
MODEL_PATH_HOST="${MODEL_PATH:-$HOME/.cache/litert_lm_models/gemma-4-E2B-it.litertlm}"
PREFILL_TOKENS="${PREFILL_TOKENS:-1024}"
DECODE_TOKENS="${DECODE_TOKENS:-256}"
ASYNC="${ASYNC:-false}"
TASKSET_MASK="${TASKSET_MASK:-f0}"
OP_PROFILING="${OP_PROFILING:-false}"

# Normalize OP_PROFILING (accept 1/true/yes/on as true).
case "${OP_PROFILING,,}" in
  1|true|yes|on)  OP_PROFILING=true  ;;
  0|false|no|off|"") OP_PROFILING=false ;;
  *)
    echo "[temp_litert.sh] OP_PROFILING must be true/false (got '${OP_PROFILING}')"
    exit 1
    ;;
esac

if [ ! -f "${MODEL_PATH_HOST}" ]; then
  echo "[temp_litert.sh] Model not found: ${MODEL_PATH_HOST}"
  echo "[temp_litert.sh] Run ./download_gemma.sh first."
  exit 1
fi
if [ -z "${ANDROID_NDK_HOME:-}" ]; then
  echo "[temp_litert.sh] ANDROID_NDK_HOME is not set. Export it before running."
  echo "    export ANDROID_NDK_HOME=/path/to/AndroidNDK"
  exit 1
fi
NDK_FALLBACK_R28B="${HOME}/neo/android-ndk-r28b"

# Auto-upgrade from a stale NDK < r28 when r28b is already installed at the
# canonical location. This handles the common case where the user has a
# `export ANDROID_NDK_HOME=.../android-ndk-r26d` line in ~/.bashrc that
# silently overrides the default set at the top of this script.
case "${ANDROID_NDK_HOME}" in
  *android-ndk-r2[0-7]*)
    if [ -f "${NDK_FALLBACK_R28B}/README.md" ] \
       && [ -f "${NDK_FALLBACK_R28B}/source.properties" ]; then
      echo "[temp_litert.sh] WARNING: caller exported ANDROID_NDK_HOME=${ANDROID_NDK_HOME}"
      echo "[temp_litert.sh]          but that NDK is too old (crate_index__cxx-1.0.149"
      echo "[temp_litert.sh]          won't compile). Auto-upgrading to:"
      echo "[temp_litert.sh]          ${NDK_FALLBACK_R28B}"
      echo "[temp_litert.sh]          To silence this warning permanently, update ~/.bashrc:"
      echo "[temp_litert.sh]            export ANDROID_NDK_HOME=${NDK_FALLBACK_R28B}"
      export ANDROID_NDK_HOME="${NDK_FALLBACK_R28B}"
    else
      echo "[temp_litert.sh] ANDROID_NDK_HOME looks like NDK < r28: ${ANDROID_NDK_HOME}"
      echo "[temp_litert.sh] crate_index__cxx-1.0.149 will not compile against this NDK's libc++."
      echo "[temp_litert.sh] Install r28b and re-run:"
      echo "    ./install_android_ndk.sh"
      echo "    unset ANDROID_NDK_HOME    # or: export ANDROID_NDK_HOME=${NDK_FALLBACK_R28B}"
      echo "    ./temp_litert.sh"
      exit 1
    fi
    ;;
esac

if [ ! -d "${ANDROID_NDK_HOME}" ]; then
  echo "[temp_litert.sh] ANDROID_NDK_HOME does not exist: ${ANDROID_NDK_HOME}"
  echo "[temp_litert.sh] Install NDK r28b or newer with:"
  echo "    ./install_android_ndk.sh"
  echo "[temp_litert.sh] or from"
  echo "    https://developer.android.com/ndk/downloads#stable-downloads"
  exit 1
fi

BAZEL=$(command -v bazelisk || command -v bazel)
if [ -z "${BAZEL}" ]; then
  echo "[temp_litert.sh] Neither bazelisk nor bazel found in PATH."
  exit 1
fi

echo "[temp_litert.sh] BAZEL=${BAZEL}"
echo "[temp_litert.sh] ANDROID_NDK_HOME=${ANDROID_NDK_HOME}"
echo "[temp_litert.sh] MODEL (host)=${MODEL_PATH_HOST}"
echo "[temp_litert.sh] DEVICE_FOLDER=${DEVICE_FOLDER}"
echo "[temp_litert.sh] PREFILL_TOKENS=${PREFILL_TOKENS}"
echo "[temp_litert.sh] DECODE_TOKENS=${DECODE_TOKENS}"
echo "[temp_litert.sh] ASYNC=${ASYNC}"
echo "[temp_litert.sh] TASKSET_MASK=${TASKSET_MASK}"
echo "[temp_litert.sh] OP_PROFILING=${OP_PROFILING}"
if [ "${OP_PROFILING}" = "false" ]; then
  echo "[temp_litert.sh]   (per-op profile summary will NOT be emitted this run."
  echo "[temp_litert.sh]    Goal of this run is to verify the decode output is"
  echo "[temp_litert.sh]    not garbled. Set OP_PROFILING=true after correctness"
  echo "[temp_litert.sh]    is confirmed to collect the matmul per-op table.)"
fi
echo ""

# ----------------------------------------------------------------------------
# 2. Build litert_lm_main for android_arm64 with GPU accelerator shlibs.
#    The two --define flags follow docs/getting-started/build-and-run.md:
#    they tell LiteRT to link the C API via a separate libLiteRtRuntimeCApi.so
#    (so the GPU accelerator shlib can dlopen it) and skip resolving the
#    C symbols statically in the main binary.
# ----------------------------------------------------------------------------
echo "[temp_litert.sh] Building //runtime/engine:litert_lm_main ..."
"${BAZEL}" build \
  --config=android_arm64 \
  --define=litert_link_capi_so=true \
  --define=resolve_symbols_in_exec=false \
  //runtime/engine:litert_lm_main

BIN=bazel-bin/runtime/engine/litert_lm_main
if [ ! -x "${BIN}" ] && [ ! -f "${BIN}" ]; then
  echo "[temp_litert.sh] Build succeeded but binary not at expected path ${BIN}"
  exit 1
fi

# Locate libLiteRt.so. With --define=litert_link_capi_so=true the C runtime
# is in a separate shared library that bazel writes somewhere under
# bazel-bin/external/litert/. Search for it instead of hard-coding the path,
# because the layout depends on rules_cc / cc_shared_library implementation
# details.
LIBLITERT_SO=$(find -L bazel-bin -maxdepth 8 -type f -name "libLiteRt.so" \
                  ! -path "*solib*" 2>/dev/null | head -1)
if [ -z "${LIBLITERT_SO}" ]; then
  # Some versions place it inside a _solib_ tree. Fall back.
  LIBLITERT_SO=$(find -L bazel-bin -type f -name "libLiteRt.so" 2>/dev/null | head -1)
fi
if [ -z "${LIBLITERT_SO}" ]; then
  echo "[temp_litert.sh] Built libLiteRt.so not found under bazel-bin/."
  echo "    Did the build target really resolve --define=litert_link_capi_so=true?"
  echo "    Try: ${BAZEL} build --config=android_arm64 --define=litert_link_capi_so=true \\"
  echo "                        --define=resolve_symbols_in_exec=false \\"
  echo "                        @litert//litert/c:libLiteRt.so"
  exit 1
fi
echo "[temp_litert.sh] libLiteRt.so : ${LIBLITERT_SO}"

# Inventory of GPU accelerator shlibs that need to live next to the binary on
# the device. These are LFS-tracked prebuilts in the upstream LiteRT-LM repo;
# this branch was imported without them. fetch_android_prebuilts.sh downloads
# them from upstream.
REQUIRED_PREBUILTS=(
  libLiteRtGpuAccelerator.so
  libLiteRtOpenClAccelerator.so
  libLiteRtTopKOpenClSampler.so
  libLiteRtTopKWebGpuSampler.so
  libLiteRtWebGpuAccelerator.so
  libGemmaModelConstraintProvider.so
)
PREBUILT_DIR=prebuilt/android_arm64
MISSING_PREBUILTS=()
for f in "${REQUIRED_PREBUILTS[@]}"; do
  if [ ! -f "${PREBUILT_DIR}/${f}" ]; then
    MISSING_PREBUILTS+=("${f}")
  fi
done
if [ "${#MISSING_PREBUILTS[@]}" -gt 0 ]; then
  echo "[temp_litert.sh] Missing GPU accelerator shlibs in ${PREBUILT_DIR}:"
  for f in "${MISSING_PREBUILTS[@]}"; do
    echo "    - ${f}"
  done
  echo "[temp_litert.sh] These are LFS-tracked in upstream LiteRT-LM. Fetch with:"
  echo "    ./fetch_android_prebuilts.sh"
  echo "[temp_litert.sh] Without them, --backend=gpu will not load any accelerator at runtime."
  exit 1
fi

# ----------------------------------------------------------------------------
# 3. Push binary + prebuilt GPU shlibs + model to device.
# ----------------------------------------------------------------------------
echo ""
echo "[temp_litert.sh] adb push binary + prebuilts + model ..."
adb shell "mkdir -p ${DEVICE_FOLDER}"
adb push "${BIN}" "${DEVICE_FOLDER}/litert_lm_main" >/dev/null
adb push "${LIBLITERT_SO}" "${DEVICE_FOLDER}/libLiteRt.so" >/dev/null

for f in "${REQUIRED_PREBUILTS[@]}"; do
  adb push "${PREBUILT_DIR}/${f}" "${DEVICE_FOLDER}/${f}" >/dev/null
done

# Model push is expensive. Only push if the on-device copy is smaller
# than the host one (assume truncated) or missing entirely.
MODEL_BASENAME=$(basename "${MODEL_PATH_HOST}")
HOST_SIZE=$(stat -c '%s' "${MODEL_PATH_HOST}" 2>/dev/null || stat -f '%z' "${MODEL_PATH_HOST}")
DEV_SIZE=$(adb shell "stat -c '%s' ${DEVICE_FOLDER}/${MODEL_BASENAME} 2>/dev/null || echo 0" | tr -d '\r')
if [ "${DEV_SIZE}" = "${HOST_SIZE}" ]; then
  echo "[temp_litert.sh] Model already on device, size matches (${HOST_SIZE} bytes). Skipping push."
else
  echo "[temp_litert.sh] Pushing model (${HOST_SIZE} bytes) ..."
  adb push "${MODEL_PATH_HOST}" "${DEVICE_FOLDER}/${MODEL_BASENAME}"
fi

adb shell "chmod +x ${DEVICE_FOLDER}/litert_lm_main"

# ----------------------------------------------------------------------------
# 4. Run with benchmark (and optionally op profiling). Capture stdout AND
#    stderr so the [PROFILE LiteRT CompiledModel per-op summary] dump from
#    the executor destructor lands in the same log as the BenchmarkInfo
#    output (when OP_PROFILING=true).
#
#    IMPORTANT: write to temp_litert_run.log, NOT error.txt. error.txt is
#    the reviewer-owned snapshot (same convention as nntrainer temp.sh).
#
#    Why default OP_PROFILING=false: empirically, SetEnableProfiling(true)
#    at CompiledModel::Create time makes LiteRT rebuild the OpenCL delegate
#    graph with instrumentation (begin/end around every op dispatch) and
#    this perturbs persistent-tensor aliasing on Adreno 830, which turns
#    the decoded Gemma 4 output into a garbage token stream. Until the
#    delegate bug is understood, the default path runs without profiling
#    so the decode output is verifiable.
# ----------------------------------------------------------------------------
RUN_LOG=temp_litert_run.log
echo ""
echo "[temp_litert.sh] Running on device (taskset ${TASKSET_MASK}, op_profiling=${OP_PROFILING})..."
adb shell "cd ${DEVICE_FOLDER}; \
  LD_LIBRARY_PATH=. \
  taskset ${TASKSET_MASK} ./litert_lm_main \
    --backend=gpu \
    --model_path=${DEVICE_FOLDER}/${MODEL_BASENAME} \
    --benchmark=true \
    --benchmark_prefill_tokens=${PREFILL_TOKENS} \
    --benchmark_decode_tokens=${DECODE_TOKENS} \
    --async=${ASYNC} \
    --report_peak_memory_footprint=true \
    --enable_op_profiling=${OP_PROFILING}" \
  2>&1 | tee "${RUN_LOG}"

# ----------------------------------------------------------------------------
# 5. Diagnostic summary (extracted from temp_litert_run.log for quick scan).
# ----------------------------------------------------------------------------
echo ""
echo "=========================================="
echo " Run summary (temp_litert.sh, OP_PROFILING=${OP_PROFILING})"
echo "=========================================="

echo ""
echo "--- input_prompt + decode output (sanity check that text is not garbled) ---"
# The decode output lands on stdout after the "input_prompt:" line that
# litert_lm_main prints. Print up to the BenchmarkInfo header so the reviewer
# can eyeball whether the model produced sensible text. If OP_PROFILING=false
# but the text is STILL garbled, the problem is NOT the profiler and we need
# to look at the OpenCL delegate / weight loading path.
awk '/^input_prompt:/{found=1} found{print; if (/BenchmarkInfo|Prefill Turn/) exit}' \
  "${RUN_LOG}" \
  || echo "(no input_prompt line found; run probably crashed before decode)"

echo ""
echo "--- Benchmark perf summary ---"
grep -E "Prefill Speed|Decode Speed|Prefill Turn|Decode Turn|Time to first token|peak memory" \
  "${RUN_LOG}" || echo "(no BenchmarkInfo lines found; run probably crashed)"

if [ "${OP_PROFILING}" = "true" ]; then
  echo ""
  echo "--- LiteRT per-op summary head (matmul / FC rows highlighted below) ---"
  awk '/PROFILE LiteRT CompiledModel per-op summary/{found=1} found{print}' "${RUN_LOG}" \
    | head -60 \
    || echo "(no per-op summary -- was --enable_op_profiling=true threaded through? Did the build include the @litert//litert/c:litert_profiler dep?)"

  echo ""
  echo "--- Matmul-like op rows (grep FullyConnected / MatMul / BatchMatMul / Conv2D) ---"
  awk '/PROFILE LiteRT CompiledModel per-op summary/{found=1} found{print}' "${RUN_LOG}" \
    | grep -E "FullyConnected|MatMul|BatchMatMul|BATCH_MATMUL|FULLY_CONNECTED|Conv2D" \
    || echo "(no matmul-like rows found in the per-op summary)"
else
  echo ""
  echo "--- Per-op profile summary: skipped (OP_PROFILING=false) ---"
  echo "To collect the matmul per-op table, re-run with:"
  echo "    OP_PROFILING=true ./temp_litert.sh"
  echo "AFTER confirming that this run produced non-garbled decode output above."
fi

echo ""
echo "Full log: ${RUN_LOG}"
echo ""
