#!/usr/bin/env bash
# temp_litert.sh
#
# One-shot build + push + run for LiteRT-LM on Android / Adreno 830.
# Mirrors the nntrainer temp.sh workflow so the same iterate/inspect loop
# works here. Produces two things the reviewer wants:
#
#   1. Prefill/Decode TPS for Gemma 4 E2B on this device (baseline vs. the
#      official "3,808 t/s prefill" number which is on Samsung S26 Ultra GPU
#      -- Adreno 830 is one or two generations older so the absolute number
#      will be lower, but we compute the ratio to peak and % utilization).
#
#   2. Per-op LiteRT profile dump, in particular every MatMul /
#      FullyConnected / BatchMatMul row, so we can see which matmul-unit-op
#      dominates prefill. This comes from the --enable_op_profiling flag we
#      added in this branch, wired through AdvancedSettings ->
#      runtime_options.SetEnableProfiling(true) ->
#      LiteRtCompiledModelGetProfiler -> LiteRtGetProfileSummary (printed
#      by the executor destructor). See the [Phase A] commit for details.
#
# Prereqs (run these once, not in this script):
#   - Bazelisk / Bazel 7.6.1   (https://bazel.build/install)
#   - Android NDK r28b+        (https://developer.android.com/ndk/downloads)
#     export ANDROID_NDK_HOME=/path/to/AndroidNDK
#   - adb with a rooted / debuggable device connected
#   - ./download_gemma.sh      (fetches the model to ~/.cache/litert_lm_models)
#
# After running this you should see a block ending with something like:
#
#   BenchmarkInfo:
#     Prefill Turns (Total 1 turns):
#       Prefill Turn 1: ...
#         Prefill Speed: <xxx.xx> tokens/sec.
#     Decode Turns (Total 1 turns):
#       Decode Turn 1: ...
#         Decode Speed: <yy.yy> tokens/sec.
#
#   [PROFILE LiteRT CompiledModel per-op summary] (generated by GetProfileSummary, --enable_op_profiling=true):
#     ... (per-op table including every matmul op) ...
#
# Paste that whole block into error.txt for the next iteration.
#
# Env overrides:
#   DEVICE_FOLDER   where to push on device (default /data/local/tmp/litert_lm)
#   MODEL_PATH      path to .litertlm on host (default ~/.cache/litert_lm_models/gemma-4-E2B-it.litertlm)
#   PREFILL_TOKENS  benchmark prefill length (default 1024, matches Google's table)
#   DECODE_TOKENS   benchmark decode length  (default 256,  matches Google's table)
#   ASYNC           async prefill flag       (default false, required when benchmark_prefill_tokens>0)
#   TASKSET_MASK    taskset mask for big core pinning (default f0 = big cluster on SD8E)

# NDK r28b or newer is required. r26d fails to compile crate_index__cxx-1.0.149
# because its libc++ does not satisfy std::ranges::contiguous_range for
# rust::Slice::iterator (see docs/getting-started/build-and-run.md).
# Respect the caller's ANDROID_NDK_HOME if already exported; otherwise default
# to r28b under ~/neo/.
export ANDROID_NDK_HOME="${ANDROID_NDK_HOME:-$HOME/neo/android-ndk-r28b}"

set -euo pipefail

# ----------------------------------------------------------------------------
# 1. Configure
# ----------------------------------------------------------------------------
DEVICE_FOLDER="${DEVICE_FOLDER:-/data/local/tmp/litert_lm}"
MODEL_PATH_HOST="${MODEL_PATH:-$HOME/.cache/litert_lm_models/gemma-4-E2B-it.litertlm}"
PREFILL_TOKENS="${PREFILL_TOKENS:-1024}"
DECODE_TOKENS="${DECODE_TOKENS:-256}"
ASYNC="${ASYNC:-false}"
TASKSET_MASK="${TASKSET_MASK:-f0}"

if [ ! -f "${MODEL_PATH_HOST}" ]; then
  echo "[temp_litert.sh] Model not found: ${MODEL_PATH_HOST}"
  echo "[temp_litert.sh] Run ./download_gemma.sh first."
  exit 1
fi
if [ -z "${ANDROID_NDK_HOME:-}" ]; then
  echo "[temp_litert.sh] ANDROID_NDK_HOME is not set. Export it before running."
  echo "    export ANDROID_NDK_HOME=/path/to/AndroidNDK"
  exit 1
fi
NDK_FALLBACK_R28B="${HOME}/neo/android-ndk-r28b"

# Auto-upgrade from a stale NDK < r28 when r28b is already installed at the
# canonical location. This handles the common case where the user has a
# `export ANDROID_NDK_HOME=.../android-ndk-r26d` line in ~/.bashrc that
# silently overrides the default set at the top of this script.
case "${ANDROID_NDK_HOME}" in
  *android-ndk-r2[0-7]*)
    if [ -f "${NDK_FALLBACK_R28B}/README.md" ] \
       && [ -f "${NDK_FALLBACK_R28B}/source.properties" ]; then
      echo "[temp_litert.sh] WARNING: caller exported ANDROID_NDK_HOME=${ANDROID_NDK_HOME}"
      echo "[temp_litert.sh]          but that NDK is too old (crate_index__cxx-1.0.149"
      echo "[temp_litert.sh]          won't compile). Auto-upgrading to:"
      echo "[temp_litert.sh]          ${NDK_FALLBACK_R28B}"
      echo "[temp_litert.sh]          To silence this warning permanently, update ~/.bashrc:"
      echo "[temp_litert.sh]            export ANDROID_NDK_HOME=${NDK_FALLBACK_R28B}"
      export ANDROID_NDK_HOME="${NDK_FALLBACK_R28B}"
    else
      echo "[temp_litert.sh] ANDROID_NDK_HOME looks like NDK < r28: ${ANDROID_NDK_HOME}"
      echo "[temp_litert.sh] crate_index__cxx-1.0.149 will not compile against this NDK's libc++."
      echo "[temp_litert.sh] Install r28b and re-run:"
      echo "    ./install_android_ndk.sh"
      echo "    unset ANDROID_NDK_HOME    # or: export ANDROID_NDK_HOME=${NDK_FALLBACK_R28B}"
      echo "    ./temp_litert.sh"
      exit 1
    fi
    ;;
esac

if [ ! -d "${ANDROID_NDK_HOME}" ]; then
  echo "[temp_litert.sh] ANDROID_NDK_HOME does not exist: ${ANDROID_NDK_HOME}"
  echo "[temp_litert.sh] Install NDK r28b or newer with:"
  echo "    ./install_android_ndk.sh"
  echo "[temp_litert.sh] or from"
  echo "    https://developer.android.com/ndk/downloads#stable-downloads"
  exit 1
fi

BAZEL=$(command -v bazelisk || command -v bazel)
if [ -z "${BAZEL}" ]; then
  echo "[temp_litert.sh] Neither bazelisk nor bazel found in PATH."
  exit 1
fi

echo "[temp_litert.sh] BAZEL=${BAZEL}"
echo "[temp_litert.sh] ANDROID_NDK_HOME=${ANDROID_NDK_HOME}"
echo "[temp_litert.sh] MODEL (host)=${MODEL_PATH_HOST}"
echo "[temp_litert.sh] DEVICE_FOLDER=${DEVICE_FOLDER}"
echo "[temp_litert.sh] PREFILL_TOKENS=${PREFILL_TOKENS}"
echo "[temp_litert.sh] DECODE_TOKENS=${DECODE_TOKENS}"
echo "[temp_litert.sh] ASYNC=${ASYNC}"
echo "[temp_litert.sh] TASKSET_MASK=${TASKSET_MASK}"
echo ""

# ----------------------------------------------------------------------------
# 2. Build litert_lm_main for android_arm64 with GPU accelerator shlibs.
#    The two --define flags follow docs/getting-started/build-and-run.md:
#    they tell LiteRT to link the C API via a separate libLiteRtRuntimeCApi.so
#    (so the GPU accelerator shlib can dlopen it) and skip resolving the
#    C symbols statically in the main binary.
# ----------------------------------------------------------------------------
echo "[temp_litert.sh] Building //runtime/engine:litert_lm_main ..."
"${BAZEL}" build \
  --config=android_arm64 \
  --define=litert_link_capi_so=true \
  --define=resolve_symbols_in_exec=false \
  //runtime/engine:litert_lm_main

BIN=bazel-bin/runtime/engine/litert_lm_main
if [ ! -x "${BIN}" ] && [ ! -f "${BIN}" ]; then
  echo "[temp_litert.sh] Build succeeded but binary not at expected path ${BIN}"
  exit 1
fi

# ----------------------------------------------------------------------------
# 3. Push binary + prebuilt GPU shlibs + model to device.
# ----------------------------------------------------------------------------
echo ""
echo "[temp_litert.sh] adb push binary + prebuilts + model ..."
adb shell "mkdir -p ${DEVICE_FOLDER}"
adb push "${BIN}" "${DEVICE_FOLDER}/litert_lm_main" >/dev/null

if ls prebuilt/android_arm64/*.so >/dev/null 2>&1; then
  adb push prebuilt/android_arm64/*.so "${DEVICE_FOLDER}/" >/dev/null
fi

# Model push is expensive. Only push if the on-device copy is smaller
# than the host one (assume truncated) or missing entirely.
MODEL_BASENAME=$(basename "${MODEL_PATH_HOST}")
HOST_SIZE=$(stat -c '%s' "${MODEL_PATH_HOST}" 2>/dev/null || stat -f '%z' "${MODEL_PATH_HOST}")
DEV_SIZE=$(adb shell "stat -c '%s' ${DEVICE_FOLDER}/${MODEL_BASENAME} 2>/dev/null || echo 0" | tr -d '\r')
if [ "${DEV_SIZE}" = "${HOST_SIZE}" ]; then
  echo "[temp_litert.sh] Model already on device, size matches (${HOST_SIZE} bytes). Skipping push."
else
  echo "[temp_litert.sh] Pushing model (${HOST_SIZE} bytes) ..."
  adb push "${MODEL_PATH_HOST}" "${DEVICE_FOLDER}/${MODEL_BASENAME}"
fi

adb shell "chmod +x ${DEVICE_FOLDER}/litert_lm_main"

# ----------------------------------------------------------------------------
# 4. Run with benchmark + op profiling. Capture stdout AND stderr so the
#    [PROFILE LiteRT CompiledModel per-op summary] dump from the executor
#    destructor lands in the same log as the BenchmarkInfo output.
#
#    IMPORTANT: write to temp_litert_run.log, NOT error.txt. error.txt is
#    the reviewer-owned snapshot (same convention as nntrainer temp.sh).
# ----------------------------------------------------------------------------
RUN_LOG=temp_litert_run.log
echo ""
echo "[temp_litert.sh] Running on device (taskset ${TASKSET_MASK})..."
adb shell "cd ${DEVICE_FOLDER}; \
  LD_LIBRARY_PATH=. \
  taskset ${TASKSET_MASK} ./litert_lm_main \
    --backend=gpu \
    --model_path=${DEVICE_FOLDER}/${MODEL_BASENAME} \
    --benchmark=true \
    --benchmark_prefill_tokens=${PREFILL_TOKENS} \
    --benchmark_decode_tokens=${DECODE_TOKENS} \
    --async=${ASYNC} \
    --report_peak_memory_footprint=true \
    --enable_op_profiling=true" \
  2>&1 | tee "${RUN_LOG}"

# ----------------------------------------------------------------------------
# 5. Diagnostic summary (extracted from temp_litert_run.log for quick scan).
# ----------------------------------------------------------------------------
echo ""
echo "=========================================="
echo " Run summary (temp_litert.sh)"
echo "=========================================="

echo ""
echo "--- Benchmark perf summary ---"
grep -E "Prefill Speed|Decode Speed|Prefill Turn|Decode Turn|Time to first token|peak memory" \
  "${RUN_LOG}" || echo "(no BenchmarkInfo lines found; run probably crashed)"

echo ""
echo "--- LiteRT per-op summary head (matmul / FC rows highlighted below) ---"
awk '/PROFILE LiteRT CompiledModel per-op summary/{found=1} found{print}' "${RUN_LOG}" \
  | head -60 \
  || echo "(no per-op summary -- was --enable_op_profiling=true threaded through? Did the build include the @litert//litert/c:litert_profiler dep?)"

echo ""
echo "--- Matmul-like op rows (grep FullyConnected / MatMul / BatchMatMul / Conv2D) ---"
awk '/PROFILE LiteRT CompiledModel per-op summary/{found=1} found{print}' "${RUN_LOG}" \
  | grep -E "FullyConnected|MatMul|BatchMatMul|BATCH_MATMUL|FULLY_CONNECTED|Conv2D" \
  || echo "(no matmul-like rows found in the per-op summary)"

echo ""
echo "Full log: ${RUN_LOG}"
echo ""
