#!/bin/sh
#
# unittest.sh - Build and run GPU (OpenCL/Adreno) unit tests on Android device
#
# Usage:
#   sh unittest.sh                    # build + push + run all GPU layer tests
#   sh unittest.sh --filter "Embed*"  # run only matching tests
#   sh unittest.sh --build-only       # build and push, skip execution
#   sh unittest.sh --run-only         # skip build, just run on device
#
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

FILTER=""
BUILD_ONLY=0
RUN_ONLY=0
DEVICE_DIR="/data/local/tmp/nntr_android_test"

for arg in "$@"; do
  case "$arg" in
    --build-only) BUILD_ONLY=1 ;;
    --run-only)   RUN_ONLY=1 ;;
    --filter)     shift; FILTER="$1" ;;
    --filter=*)   FILTER="${arg#--filter=}" ;;
  esac
  shift 2>/dev/null || true
done

if [ -n "$ADB_IP" ]; then
  ADB_CMD="adb -H ${ADB_IP}"
else
  ADB_CMD="adb"
fi

# =============================================================================
# Step 1: Build nntrainer with OpenCL
# =============================================================================
if [ $RUN_ONLY -eq 0 ]; then
  echo "=========================================="
  echo "[Step 1/4] Building nntrainer (OpenCL)"
  echo "=========================================="

  # Build libnntrainer.so with OpenCL support
  ./tools/package_android.sh \
    -Denable-opencl=true \
    -Denable-fp16=true \
    -Domp-num-threads=1

  # ==========================================================================
  # Step 2: Build test executables with ndk-build
  # ==========================================================================
  echo ""
  echo "=========================================="
  echo "[Step 2/4] Building test executables"
  echo "=========================================="

  cd test/jni
  ndk-build -j$(nproc) MESON_ENABLE_OPENCL=1 unittest_layers
  if [ $? -ne 0 ]; then
    echo "[ERROR] ndk-build failed"
    exit 1
  fi
  cd "$SCRIPT_DIR"

  # ==========================================================================
  # Step 3: Push to device
  # ==========================================================================
  echo ""
  echo "=========================================="
  echo "[Step 3/4] Pushing to device"
  echo "=========================================="

  $ADB_CMD shell mkdir -p ${DEVICE_DIR}/res

  # Push test binaries
  $ADB_CMD push test/libs/arm64-v8a/* ${DEVICE_DIR}/

  # Push golden data (generated by meson build)
  if [ ! -d build ]; then
    meson build \
      -Denable-opencl=true \
      -Denable-fp16=true \
      -Dopenblas-num-threads=1 \
      -Domp-num-threads=1 \
      -Denable-tflite-interpreter=false \
      -Denable-tflite-backbone=false \
      -Dhgemm-experimental-kernel=false
  fi
  $ADB_CMD push build/res/ ${DEVICE_DIR}/

  echo "[OK] Push complete"
fi

if [ $BUILD_ONLY -eq 1 ]; then
  echo ""
  echo "[Done] Build-only mode. Skipping execution."
  exit 0
fi

# =============================================================================
# Step 4: Run tests on device
# =============================================================================
echo ""
echo "=========================================="
echo "[Step 4/4] Running tests on device"
echo "=========================================="

$ADB_CMD shell chmod +x ${DEVICE_DIR}/unittest_layers

# Build gtest filter
if [ -n "$FILTER" ]; then
  GTEST_FILTER="--gtest_filter=${FILTER}"
else
  # Default: run all GPU layer tests
  GTEST_FILTER="--gtest_filter=*GPU*"
fi

echo "Filter: ${GTEST_FILTER}"
echo ""

$ADB_CMD shell "cd ${DEVICE_DIR} && export LD_LIBRARY_PATH=. && ./unittest_layers ${GTEST_FILTER}"

echo ""
echo "=========================================="
echo "[Done] Test execution complete"
echo "=========================================="
